# -*- coding: utf-8 -*-
"""
/***************************************************************************
 RAAloader
                                 A QGIS plugin
 Download data from RAÄs Öppna data-portal
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2026-02-18
        copyright            : (C) 2026 by Andrew Mercer
        email                : mercerraa@gmail.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load RAAloader class from file RAAloader.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .raa_loader import RAAloader
    return RAAloader(iface)
